#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# numlockx on &
feh --bg-fill /home/op3nk0d3/.local/share/backgrounds/wall1.jpg &
/home/op3nk0d3/.config/polybar/launch.sh
/home/op3nkod3/.config/dunst/launch.sh
picom -f &
/usr/bin/lxpolkit &
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Firefox Developer Edition" desktop='^1' tiled=on follow=on
bspc rule -a Code desktop='^2' tiled=on follow=on
bspc rule -a kitty desktop='^3' follow=on tiled=on
bspc rule -a Thunar desktop='^4' follow=on tiled=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
